// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go-grpc-example/10-grpc-gateway/proto/simple.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InnerMessage struct {
	// some_integer can only be in range (1, 100).
	SomeInteger int32 `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	// some_float can only be in range (0;1).
	SomeFloat            float64  `protobuf:"fixed64,2,opt,name=some_float,json=someFloat,proto3" json:"some_float,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerMessage) Reset()         { *m = InnerMessage{} }
func (m *InnerMessage) String() string { return proto.CompactTextString(m) }
func (*InnerMessage) ProtoMessage()    {}
func (*InnerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_138a68933bf1431e, []int{0}
}

func (m *InnerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerMessage.Unmarshal(m, b)
}
func (m *InnerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerMessage.Marshal(b, m, deterministic)
}
func (m *InnerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerMessage.Merge(m, src)
}
func (m *InnerMessage) XXX_Size() int {
	return xxx_messageInfo_InnerMessage.Size(m)
}
func (m *InnerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_InnerMessage proto.InternalMessageInfo

func (m *InnerMessage) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

func (m *InnerMessage) GetSomeFloat() float64 {
	if m != nil {
		return m.SomeFloat
	}
	return 0
}

type OuterMessage struct {
	// important_string must be a lowercase alpha-numeric of 5 to 30 characters (RE2 syntax).
	ImportantString string `protobuf:"bytes,1,opt,name=important_string,json=importantString,proto3" json:"important_string,omitempty"`
	// proto3 doesn't have `required`, the `msg_exist` enforces presence of InnerMessage.
	Inner                *InnerMessage `protobuf:"bytes,2,opt,name=inner,proto3" json:"inner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OuterMessage) Reset()         { *m = OuterMessage{} }
func (m *OuterMessage) String() string { return proto.CompactTextString(m) }
func (*OuterMessage) ProtoMessage()    {}
func (*OuterMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_138a68933bf1431e, []int{1}
}

func (m *OuterMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OuterMessage.Unmarshal(m, b)
}
func (m *OuterMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OuterMessage.Marshal(b, m, deterministic)
}
func (m *OuterMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OuterMessage.Merge(m, src)
}
func (m *OuterMessage) XXX_Size() int {
	return xxx_messageInfo_OuterMessage.Size(m)
}
func (m *OuterMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OuterMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OuterMessage proto.InternalMessageInfo

func (m *OuterMessage) GetImportantString() string {
	if m != nil {
		return m.ImportantString
	}
	return ""
}

func (m *OuterMessage) GetInner() *InnerMessage {
	if m != nil {
		return m.Inner
	}
	return nil
}

func init() {
	proto.RegisterType((*InnerMessage)(nil), "proto.InnerMessage")
	proto.RegisterType((*OuterMessage)(nil), "proto.OuterMessage")
}

func init() {
	proto.RegisterFile("go-grpc-example/10-grpc-gateway/proto/simple.proto", fileDescriptor_138a68933bf1431e)
}

var fileDescriptor_138a68933bf1431e = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x6a, 0xe3, 0x30,
	0x14, 0xc6, 0xe3, 0x30, 0x0e, 0x13, 0xc5, 0xcc, 0x64, 0x34, 0x10, 0x42, 0x08, 0x38, 0x98, 0x59,
	0x84, 0x99, 0x71, 0xd4, 0xb8, 0xa4, 0x8b, 0x42, 0x29, 0x78, 0x51, 0xc8, 0xa2, 0x84, 0x3a, 0xab,
	0x52, 0xda, 0xa0, 0x24, 0xaa, 0x2a, 0x6a, 0x4b, 0x46, 0x56, 0x92, 0xfe, 0xa1, 0x50, 0x7a, 0x85,
	0x1e, 0xad, 0x07, 0x30, 0x98, 0x1e, 0xa0, 0x47, 0x28, 0x96, 0x9b, 0x34, 0x8b, 0x6a, 0xf3, 0xf4,
	0xf4, 0xfd, 0x9e, 0xde, 0xfb, 0x24, 0xe0, 0x51, 0xe1, 0x52, 0x19, 0xcf, 0x5c, 0x72, 0x83, 0xa3,
	0x38, 0x24, 0xa8, 0xbf, 0x53, 0xe4, 0x14, 0x2b, 0xb2, 0xc2, 0xb7, 0x28, 0x96, 0x42, 0x09, 0x94,
	0xb0, 0x5c, 0xec, 0xe9, 0x04, 0x9a, 0x3a, 0xb4, 0xf6, 0x28, 0x53, 0x57, 0x8b, 0x69, 0x6f, 0x26,
	0x22, 0x14, 0xad, 0x98, 0xba, 0x16, 0x2b, 0x44, 0x85, 0xab, 0x45, 0x77, 0x89, 0x43, 0x36, 0xc7,
	0x4a, 0xc8, 0x04, 0x6d, 0xb6, 0x45, 0x79, 0xab, 0x4d, 0x85, 0xa0, 0x21, 0x41, 0x38, 0x66, 0x08,
	0x73, 0x2e, 0x14, 0x56, 0x4c, 0xf0, 0xa4, 0x50, 0x1d, 0x09, 0xac, 0x21, 0xe7, 0x44, 0x1e, 0x93,
	0x24, 0xc1, 0x94, 0xc0, 0x7f, 0xc0, 0x4a, 0x44, 0x44, 0x26, 0x8c, 0x2b, 0x42, 0x89, 0x6c, 0x1a,
	0x1d, 0xa3, 0x6b, 0xfa, 0xdf, 0xb3, 0xd4, 0xfe, 0x56, 0x2f, 0x35, 0xe7, 0x41, 0x2d, 0x57, 0x87,
	0x85, 0x08, 0x07, 0x00, 0x68, 0xf8, 0x32, 0x14, 0x58, 0x35, 0xcb, 0x1d, 0xa3, 0x6b, 0xf8, 0x8d,
	0x2c, 0xb5, 0xe1, 0xb0, 0xf4, 0xb1, 0x4e, 0x8a, 0xf0, 0x76, 0x18, 0x54, 0x73, 0xf2, 0x28, 0x07,
	0x9d, 0x47, 0x03, 0x58, 0xa3, 0x85, 0xfa, 0x6c, 0x7a, 0x00, 0xea, 0x2c, 0x8a, 0x85, 0x54, 0x98,
	0xab, 0x49, 0xa2, 0x24, 0xe3, 0x54, 0x37, 0xae, 0xfa, 0x30, 0x4b, 0xed, 0x1f, 0xc0, 0xba, 0x38,
	0xc3, 0xee, 0xdd, 0xf9, 0xbd, 0xf7, 0x7f, 0xf0, 0xf0, 0x27, 0xf8, 0xb9, 0x61, 0xc7, 0x1a, 0x85,
	0x7d, 0x60, 0xb2, 0xdc, 0x83, 0x9e, 0xa0, 0xe6, 0xfd, 0x2e, 0xac, 0xf5, 0xb6, 0x7d, 0xf9, 0x95,
	0x2c, 0xb5, 0xcb, 0x1d, 0x23, 0x28, 0x48, 0xef, 0x14, 0x54, 0xc6, 0xfa, 0x8d, 0xe1, 0x08, 0x98,
	0x81, 0x58, 0x28, 0x02, 0xbf, 0x2a, 0x6b, 0xad, 0x0f, 0xb7, 0xc7, 0x75, 0xda, 0x4f, 0x2f, 0xaf,
	0xcf, 0xe5, 0x86, 0xf3, 0x0b, 0x2d, 0xfb, 0x68, 0xfd, 0x91, 0x32, 0xbf, 0x64, 0xdf, 0xf8, 0x3b,
	0xad, 0xe8, 0x8a, 0xdd, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x54, 0x5d, 0xe0, 0xec, 0xeb, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SimpleClient is the client API for Simple service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SimpleClient interface {
	Route(ctx context.Context, in *InnerMessage, opts ...grpc.CallOption) (*OuterMessage, error)
}

type simpleClient struct {
	cc *grpc.ClientConn
}

func NewSimpleClient(cc *grpc.ClientConn) SimpleClient {
	return &simpleClient{cc}
}

func (c *simpleClient) Route(ctx context.Context, in *InnerMessage, opts ...grpc.CallOption) (*OuterMessage, error) {
	out := new(OuterMessage)
	err := c.cc.Invoke(ctx, "/proto.Simple/Route", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimpleServer is the server API for Simple service.
type SimpleServer interface {
	Route(context.Context, *InnerMessage) (*OuterMessage, error)
}

// UnimplementedSimpleServer can be embedded to have forward compatible implementations.
type UnimplementedSimpleServer struct {
}

func (*UnimplementedSimpleServer) Route(ctx context.Context, req *InnerMessage) (*OuterMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Route not implemented")
}

func RegisterSimpleServer(s *grpc.Server, srv SimpleServer) {
	s.RegisterService(&_Simple_serviceDesc, srv)
}

func _Simple_Route_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InnerMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleServer).Route(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Simple/Route",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleServer).Route(ctx, req.(*InnerMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Simple_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Simple",
	HandlerType: (*SimpleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Route",
			Handler:    _Simple_Route_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go-grpc-example/10-grpc-gateway/proto/simple.proto",
}
